### PR TITLE
Unbundle SCons, use recent SCons, fix test dependencies

### PR DESCRIPTION
**Pull request by dmaone**
There is no more good reason to bundle SCons.

### CODE REVIEW

**Review by timburke — COMMENTED** [review]
Changes look fine to me but I have no way of testing to make sure our firmware still builds without bundled scons.  It _should_ but it would be bad if it didn't.  

So, deferring to @x24ling, @anwu and @ekkizogloy to verify if unbundling and using a pip installed scons works as expected and we can still build our POD projects.

**Comment by dmaone** [comment]
> It _should_ but it would be bad if it didn't.

There are actual tests for that. That literally run `iotile build` from commandline.
But no rush.

Whoever will be building - don't forget to `pip remove` everything and `pip install` (possibly `pip install -e`?) back.

**Review by anwu — APPROVED** [review]
LGTM.

I was able to create a new python 3.8 environment and I `pip install -e` all these remote changes. I build all of the components of `pod_controller` with this.

**Review by x24ling — APPROVED** [review]
```
(test-update-scons) PS C:\Users\ChrisLing\iotile\coretools\iotilebuild\test> pytest .
================================================= test session starts =================================================
platform win32 -- Python 3.8.10, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: C:\Users\ChrisLing\iotile\coretools\iotilebuild, configfile: pytest.ini
collected 58 items

test_template.py ....                                                                                            [  6%]
test_build\test_architecturegroups.py .                                                                          [  8%]
test_depresolvers\test_dependency_conflict.py ...                                                                [ 13%]
test_depresolvers\test_resolverchain.py .....                                                                    [ 22%]
test_dev\test_resolverchain_basic.py .                                                                           [ 24%]
test_iotilebuild\test_scons.py ..............s....                                                               [ 56%]
test_release\test_release.py ...........                                                                         [ 75%]
test_tilebus\test_parse_mib.py ..............                                                                    [100%]

================================================== warnings summary ===================================================
..\..\..\env\test-update-scons\lib\site-packages\pyreadline\py3k_compat.py:8
  c:\users\chrisling\iotile\env\test-update-scons\lib\site-packages\pyreadline\py3k_compat.py:8: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
    return isinstance(x, collections.Callable)

test_iotilebuild\python_data_bundling\python\support\test_app.py:4
  C:\Users\ChrisLing\iotile\coretools\iotilebuild\test\test_iotilebuild\python_data_bundling\python\support\test_app.py:4: PytestCollectionWarning: cannot collect test class 'TestApp' because it has a __init__ constructor (from: test/test_iotilebuild/python_data_bundling/python/support/test_app.py)
    class TestApp(IOTileApp):

-- Docs: https://docs.pytest.org/en/stable/warnings.html
```

**Pull request merged**
