### PR TITLE
Fix regression in ProductResolver

### LINKED ISSUE #433: Regression in iotile-build building projects with tilebus definitions or include_directories
The `ProductResolver` does not support `module_settings.json` files with arrays of values for a given key.

### PR DESCRIPTION
**Pull request by timburke**
Closes #433

### CODE REVIEW

**Comment by x24ling** [comment]
Is your current implementation just to skip adding the "include_directories" and "tilebus_definitions" to the ProductResolver?

**Comment by timburke** [comment]
Yeah, there's not a use case right now for resolving those from other products so it was the quickest solution

**Comment by timburke** [comment]
Yup, sorry that didn't get pushed.  Thanks for catching that.

**Comment by timburke** [comment]
I added https://github.com/iotile/coretools/issues/435 to track a future enhancement where we support resolving tilebus definitions and include_directories

**Pull request merged**
